[package]
name = "static-files"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = "0.6.20"
futures = "0.3"
tokio = "1.34"
tokio-util = { version = "0.7", features = ["io"] }
tower-http = { version = "0.4.4", features = ["fs"] }
